#!/bin/bash
PROTECTED_BRANCHES=("master")
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Block committing protected branches
for BRANCH in "${PROTECTED_BRANCHES[@]}"; do
  if [[ $BRANCH == $CURRENT_BRANCH ]]; then
    echo "You can't commit at $BRANCH branch"
    exit 1
  fi
done

npm lint
